### ISSUE TITLE
Valores PIB. ¿Son bde_series_load(3777060, series_label = "GDP_quarterly_value")  ?...

### ISSUE THREAD

**Issue by coforfe** [rOpenSpain/tidyBdE#13]
Hola @dieghernan ,

Estoy comprobando los resultados de la nueva función para el `gdp` y veo estos resultados:

```r
> gdp <- bde_series_load(3777060, series_label = "GDP_quarterly_value") 
> tail(gdp)
# A tibble: 6 × 2
  Date       GDP_quarterly_value
  <date>                   <dbl>
1 2019-12-01              324901
2 2020-03-01              289961
3 2020-06-01              250838
4 2020-09-01              281956
5 2020-12-01              298943
6 2021-03-01              280524
```
Y vaya, los resultados no me cuadran con los valores del PIB que tenía en mente. Nuestro PIB es del orden del `1.2MM€` (un billón doscientos mil...). 

Gracias de nuevo!
Carlos.

_Originally posted by @coforfe in https://github.com/rOpenSpain/tidyBdE/issues/6#issuecomment-893392303_

**Comment by coforfe** [comment]
Hola,

Ah, que creo que son datos corregidos de efectos estacionales.

Gracias,
Carlos.

**Comment by dieghernan** [comment]
Justo, en el artículo de la web lo calculo asi:

https://github.com/rOpenSpain/tidyBdE/blob/4c6a9d8784b3b9f45d714c21c195c11678023132/vignettes/articles/Main_Macroeconomic_Series.Rmd#L38-L40

**Comment by coforfe** [comment]
OK. 
Muchas Gracias!
