### ISSUE TITLE
Función "bde_ind_gdp_quarterly()"...

### ISSUE THREAD

**Issue by coforfe** [rOpenSpain/tidyBdE#6]
Hola Diego,

Primeramente darte las gracias por crear este paquete.

Estoy viendo la forma de poder conseguir los mismos datos de "PIB" trimestral como los que tienes en el [artículo](https://ropenspain.github.io/tidyBdE/articles/articles/Main_Macroeconomic_Series.html#gdp-per-capita). Y claro, en el propio código de la viñetea aparece una función `bde_ind_gdp_quarterly()` que ahora veo que no está disponible. Solo veo la variación `bde_ind_gdp_var()`. 

¿Sería posible el volver incluirla como función?.
O vaya, si no esposible, cómo podría acceder a los datos trimestrales. He estado buscando con `bde_catalog_search()" y no he sido capaz de encontrarla.

Gracias!
Calos Ortega.

**Comment by dieghernan** [comment]
Hola @coforfe :

Esa función está disponible en la versión actualmente en desarrollo. Puedes extraer la serie con la versión CRAN de la siguiente manera:

```r

bde_series_load(3777060, series_label = "GDP_quarterly_value")

```

También tienes la opción de instalar la versión en desarrollo de `tidyBdE` y usar la función directamente:

```r

options(repos = c(
    ropenspain = 'https://ropenspain.r-universe.dev',
    CRAN = 'https://cloud.r-project.org'))

# Install tidyBdE
install.packages('tidyBdE')

bde_ind_gdp_quarterly()


```

Saludos

**Comment by coforfe** [comment]
Hola Diego!

Perfecto!.
Muchas Gracias!
Carlos.

**Comment by dieghernan** [comment]
#12 la versión 0.2.0 acaba de ser subida a CRAN, las funciones que comentabas están incluidas 😉

**Comment by coforfe** [comment]
Hola Diego.

Muchas Gracias!.
Lo pruebo y te comento.

Gracias de nuevo,
Carlos.

**Comment by coforfe** [comment]
Hola @dieghernan ,

Estoy comprobando los resultados de la nueva función para el `gdp` y veo estos resultados:

```r
> gdp <- bde_series_load(3777060, series_label = "GDP_quarterly_value") 
> tail(gdp)
# A tibble: 6 × 2
  Date       GDP_quarterly_value
  <date>                   <dbl>
1 2019-12-01              324901
2 2020-03-01              289961
3 2020-06-01              250838
4 2020-09-01              281956
5 2020-12-01              298943
6 2021-03-01              280524
```
Y vaya, los resultados no me cuadran con los valores del PIB que tenía en mente. Nuestro PIB es del orden del `1.2MM€` (un billón doscientos mil...). 

Gracias de nuevo!
Carlos.
